import { IR, ModelDefinition, ServiceDefinition } from '@nestsync/analyzer';
import { TransportPlugin } from './plugin';
import { AxiosPlugin } from './plugins/axios';

export function emitTypeScriptSdk(ir: IR, plugin: TransportPlugin = AxiosPlugin): string {
  let code = `// ==========================================\n`;
  code += `// AUTO-GENERATED BY NESTSYNC\n`;
  code += `// CLIENT: ${plugin.name.toUpperCase()}\n`;
  code += `// ==========================================\n\n`;

  code += plugin.generateImports() + '\n';

  if (plugin.generateCoreClient) {
    code += plugin.generateCoreClient() + '\n';
  }

  code += generateInterfaces(ir.models);
  code += generateClient(ir.services, plugin);

  if (plugin.generateExtra) {
    code += `\n// --- EXTENSIONS ---\n\n`;
    code += plugin.generateExtra(ir.services);
  }

  return code;
}

// --- Internal Generators ---

function generateInterfaces(models: Record<string, ModelDefinition>): string {
  let output = '';

  for (const [name, model] of Object.entries(models)) {
    output += `export interface ${name} {\n`;

    for (const prop of model.properties) {
      const optionalFlag = prop.isOptional ? '?' : '';
      const arrayFlag = prop.isArray ? '[]' : '';

      if (prop.description) {
        output += `  /**\n`;
        const lines = prop.description.split('\\n');
        for (const line of lines) {
          output += `   * ${line}\n`;
        }
        output += `   */\n`;
      }

      output += `  ${prop.name}${optionalFlag}: ${prop.type}${arrayFlag};\n`;
    }

    output += `}\n\n`;
  }

  return output;
}

function generateClient(services: ServiceDefinition[], plugin: TransportPlugin): string {
  let output = `export const sdk = {\n`;

  for (const svc of services) {
    const svcName = svc.name.replace('Controller', '').toLowerCase();
    output += `  ${svcName}: {\n`;

    for (const method of svc.methods) {
      const args: string[] = [];
      const hasQuery = method.query.length > 0;

      // 1. Path Params
      if (method.params.length > 0) {
        const paramArgs = method.params.map(p => `${p.name}: ${p.type}`).join(', ');
        args.push(paramArgs);
      }

      // 2. Query Params
      if (hasQuery) {
        const queryInterface = method.query
          .map(q => `${q.name}${q.isOptional ? '?' : ''}: ${q.type}`)
          .join(', ');
        args.push(`query: { ${queryInterface} }`);
      }

      // 3. Body
      if (method.bodyType && method.bodyType !== 'undefined') {
        args.push(`data: ${method.bodyType}`);
      }

      // 4. Plugin (Ex: AxiosRequestConfig vs RequestInit)
      const configType = plugin.getConfigType();
      args.push(`config?: ${configType}`);

      const argsString = args.join(', ');

      // "/users/${id}"
      let fullPath = `${svc.basePath}${method.path}`.replace(/\/\//g, '/');
      method.params.forEach(p => {
        fullPath = fullPath.replace(`:${p.name}`, `\${${p.name}}`);
      });

      output += `    ${method.name}: async (${argsString}): Promise<${method.returnType}> => {\n`;

      output += plugin.generateMethodBody(method, fullPath, hasQuery);

      output += `    },\n`;
    }

    output += `  },\n`;
  }

  output += `};\n`;
  return output;
}

export { AxiosPlugin } from './plugins/axios';
export { FetchPlugin } from './plugins/fetch';
export { ReactQueryPlugin } from './plugins/react-query';
